/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



var index = 0

var dictionary = new Array(
	"abacus",		"frame with balls for calculating",
	"abate",		"to lessen, to subside ",
	"abdication",	"giving up control, authority ",
	"abdomen",	"stomach and bowels",
	"aberration",	"straying away from what is normal",
	"abeyance",	"suspended action",
	"abhor",	"to hate, to detest",
	"abide",	"be faithful to; endure",
	"abjure",	"promise or swear to give up",
	"abraded",	"rubbed off, worn away by friction",
	"abrasion",	"rubbing, scraping, wearing off",
	"abrogate",	"repeal or annul by authority",
	"abscond",	"to go away suddenly (to avoid arrest)",
	"abstruse",	"difficult to comprehend; obscure",
	"abundant",	"plentiful",
	"abut",	"border on",
	"abysmal",	"bottomless, extreme",
	"acarpous",	"effete, no longer fertile, worn out",
	"accentuate",	"give more force or attention to",
	"acclaimed",	"welcomed with shouts and approval",
	"accolade",	"praise, approval",
	"accretion",	"the growing of separate things into one",
	"acquiesce",	"in agree (without protest)",
	"acquisition",	"smth acquired, acquiring",
	"adamant",	"kind of stone; inflexible",
	"adhere",	"remain faithful, stick fast to",
	"adhesion",	"adhering, support",
	"adjacent",	"lying near, next",
	"admonitory",	"containing warning",
	"adorn",	"add beauty; decorate",
	"adulteration",	"making unpure, poorer in quality",
	"affinity",	"close connection, relationship",
	"aggravate",	"make worse; irritate",
	"agile",	"active, quick-moving",
	"ail",	"trouble; be ill",
	"alacrity",	"eager and cheerful readiness",
	"alienate",	"estrange",
	"allegiance",	"duty, support, loyalty",
	"alleviate",	"make (pain) easier to bear",
	"alloy",	"to debase by mixing with something inferior",
	"aloof",	"reserved, indifferent",
	"amalgamate",	"mix, combine, unite societies",
	"ambidextrous",	"able to use the left hand or the right equally well",
	"ambiguous",	"doubtful, uncertain",
	"ambivalent",	"having both of two contrary meanings",
	"ameliorate",	"improve, make better",
	"amendment",	"improving",
	"amicable",	"friendly",
	"amortize",	"end (a debt) by setting aside money",
	"amplify",	"make large or fuller, increase the strength",
	"animosity",	"strong dislike",
	"annul",	"put an end to",
	"anticlimax",	"sudden fall",
	"antidote",	"medicine used against a poison or a disease",
	"antithetical",	"direct opposing",
	"apartheid",	"brutal racial discrimination",
	"apathetic",	"indifference",
	"aplomb",	"self-confidence",
	"apostate",	"one who abandons long-held religious or political convictions",
	"apotheosis",	"deification, glorification to godliness",
	"appease",	"make quiet or calm",
	"apprehensive",	"grasping, understanding; fear, unhappy feeling about future",
	"apprise",	"give notice to, inform",
	"approbation",	"approval",
	"appropriate",	"take for one's own use, acquire, set aside",
	"apropos",	"appropriate to the situation; apt",
	"apt",	"well-suited, quick-witted",
	"arabesque",	"a complex, ornate design",
	"arabesque",	"whimsical",
	"arbitrate",	"decide by arbitration",
	"arboreal",	"of connected with trees",
	"ardently",	"with full of ardor",
	"ardor",	"enthusiasm",
	"arduous",	"steep, difficult ascent; laborious",
	"argot",	"jargon, slang",
	"arrant",	"in the highest degree",
	"arrogance",	"proud, superior manner of behaviour",
	"articulate",	"speak distinctly, connect by joints",
	"ascend",	"go or come up",
	"ascent",	"the act of ascending",
	"ascertain",	"get to know",
	"ascetic",	"practicing self-denial, austere, stark",
	"ascribe",	"consider to be the origin of or belonging to",
	"asperity",	"roughness, harshness, ill temper, irritability",
	"aspersion",	"slander",
	"assail",	"with attack violently",
	"asset",	"valuable quality, smth that has money value",
	"assiduous",	"diligent, hard-working, sedulous",
	"assuage",	"make smth (pain, desire) less",
	"assumption",	"smth supposed but not proved",
	"asterisk",	"the mark * (e.g.. omitted letters)",
	"astringent",	"substance that shrinks",
	"astute",	"clever; quick at seeing to get an advantage",
	"atonement",	"repayment; death of Jesus",
	"attenuate",	"make thin. weaken, enervate",
	"audacious",	"daring, foolishly bold, impudent",
	"augury",	"omen, sign",
	"august",	"majestic, venerable",
	"auspice",	"protection or support, patronage",
	"auspicious",	"favorable, successful, prosperous",
	"austere",	"severely moral and strict; simple and plain",
	"auxiliary",	"helping, supporting",
	"aver",	"affirm, assert, prove, justify",
	"aversion",	"strong dislike",
	"avid",	"eager, greedy",
	"avow",	"admit. Declare openly",
	"baleful",	"harmful, ominous, causing evil",
	"balk",	"obstacle; purposely to get on the way of",
	"balloon",	"swell out like balloon",
	"balm",	"sweet-smelling oil; consolation",
	"banal",	"uninteresting",
	"band",	"flat, thin strip of material; range of frequencies",
	"bane",	"cause of injury, poison, source of harm",
	"baneful",	"causing harm or ruin, pernicious, destructive",
	"barrage",	"artificial obstacle built across a river",
	"barren",	"not good enough, unable to have young ones, without value",
	"bask",	"in enjoy warmth and light",
	"bazaar",	"market",
	"be",	"irreconcilable cannot be brought into harmony",
	"beatify",	"to bless, make happy, or ascribe a virtue to",
	"bedizen",	"to adorn, especially in a cheap, showy manner",
	"belie",	"contradict, give a false impression",
	"belittle",	"cause to seem unimportant",
	"bellicose",	"belligerent, pugnacious, warlike",
	"belligerent",	"(person, nation) waging war",
	"belligerently",	"waging war",
	"bend",	"cause smth to be out of a straight line",
	"benefactor",	"person who has given help",
	"benevolence",	"wish or activity in doing good",
	"benign",	"kind and gentle; mild (climate)",
	"bequest",	"arrangement to give smth at death",
	"berate",	"scold sharply",
	"bereft",	"rob or dispossess of smth (material)",
	"bewilder",	"puzzle, confuse",
	"biased",	"prejudice",
	"bigot",	"stubborn, narrow-minded person",
	"bilge",	"bulge, the protuberance of a cask",
	"blandishment",	"flattery, coaxing",
	"blandness",	"polite manner, comforting, uninteresting",
	"blatant",	"noisy and rough",
	"blithe",	"cheerful, casual, carefree",
	"blithe",	"gay and joyous",
	"blueprint",	"plan, scheme, photographic print",
	"blunt",	"plain, not troubling to be polite",
	"boggle",	"be alarmed, hesitate, amazed",
	"bogus",	"sham, counterfeit, not genuine",
	"boisterous",	"loud, noisy, rough, lacking restraint",
	"bolster",	"give greatly needed support",
	"boorish",	"crude, offensive, rude",
	"braid",	"strands of hair woven together, smth edging sloth",
	"brash",	"hasty, rush; cheeky, saucy",
	"brass",	"yellow metal (mixing copper and zinc)",
	"brazen",	"made of brass",
	"breach",	"opening, broken place, breaking",
	"brisk",	"active, lively",
	"brisket",	"breast of an animal",
	"brittle",	"easily broken",
	"broach",	"bring up, announce, begin to talk about",
	"brook",	"to tolerate, endure",
	"buoyant",	"able to float; light-hearted",
	"burgeon",	"grow forth, send out buds",
	"burnish",	"to polish, rub to a shine",
	"bust",	"run out of money",
	"cabal",	"a scheme or plot, a group of plotters",
	"cadge",	"to beg, to get by begging",
	"calipers",	"metal supports attached to the legs, measuring instrument",
	"calumniate",	"to slander, present false accusal",
	"calumny",	"slander, aspersion",
	"candid",	"frank, straight-forward",
	"canvass",	"discuss thoroughly; sort of touting",
	"capricious",	"fickle, whimsical, given to change, unpredictable",
	"castigate",	"to chastise, correct by punishing",
	"castigation",	"severe punishment",
	"casual",	"happening by chance, careless",
	"catalyst",	"substance that causes speeding up",
	"caustic",	"biting, sarcastic",
	"censure",	"expression of blame or disapproval; a rebuke",
	"census",	"official counting of the population",
	"centurion",	"leader of a unit of 100 soldiers",
	"chary",	"cautious, wary",
	"chastened",	"corrected, punished",
	"chastisement",	"punishment",
	"chauvinist",	"a blindly devoted patriot",
	"chisel",	"steel tool for shaping materials",
	"churl",	"bad-tempered person",
	"cite",	"give as an example",
	"clamor",	"shout, complain with a lot of noise",
	"cleanse",	"make pure, thoroughly clean",
	"cling",	"to resist separation",
	"clot",	"half-solid lump formed from liquid",
	"cloture",	"closing, device (in Parliament) to end a debate by voting",
	"coalescing",	"coming together and uniting into one substance",
	"coax",	"get smb to do smth by kindness",
	"coddle",	"treat with care and tenderness",
	"coerce",	"compel, to force to make obedient",
	"coeval",	"of the same period, coexisting",
	"cogent",	"strong, convincing",
	"cogitate",	"think deeply, mediate",
	"cognition",	"knowing, awareness (emotionless)",
	"cognizant",	"being fully aware of",
	"coherent",	"sticking together",
	"colander",	"bowl-shaped vessel with many holes used to drain off water",
	"collaborate",	"work in partnership",
	"collusion",	"secret agreement for a deceitful purpose",
	"combustion",	"process of burning",
	"commemorate",	"keep the memory of",
	"commend",	"praise",
	"commendable",	"worthy of praise",
	"commingle",	"mingle together",
	"commuter",	"person who travels regularly",
	"complacently",	"with self-satisfaction",
	"complaisance",	"tending to comply, obliging, willingness to please",
	"comply",	"act in accordance",
	"compound",	"mix or combine",
	"comprise",	"be composed of",
	"compunction",	"feeling of regret for one's action",
	"conceal",	"hide, keep secret",
	"conceit",	"over-high opinion of, too much pride",
	"conciliatory",	"reconciling, soothing, comforting, mollifying",
	"concord",	"agreement or harmony",
	"concur",	"agree in opinion, happen together",
	"condense",	"increase in density, strength, make laconic",
	"condone",	"forgive",
	"congeal",	"make or become stiff and solid",
	"conjoin",	"to join together",
	"connoisseur",	"a person with good judgement (e.g.. in art)",
	"connotation",	"suggestion in addition to",
	"consent",	"give agreement or permission",
	"consequential",	"pompous, self important",
	"consolation",	"consoling or being consoled",
	"console",	"give comfort or sympathy to",
	"conspicuous",	"easily seen; remarkable",
	"consternation",	"surprise and fear, dismay",
	"constrict",	"make tight or smaller",
	"consume",	"get to the end of",
	"contemn",	"to scorn or despise",
	"contentious",	"argumentative, pugnacious, combative, quarrelsome",
	"contiguous",	"touching, neighboring, near",
	"contrite",	"filled with deep sorrow for wrongdoing",
	"contumacious",	"insubordinate, rebellious",
	"conundrum",	"a riddle, dilemma, enigma",
	"conviction",	"convincing; firm belief",
	"convoke",	"call together, summon",
	"convoluted",	"complicated; coiled, twisted",
	"cord",	"twisted strands",
	"cordial",	"warm and sincere",
	"cordon",	"line (of police acting as a guard)",
	"corporeal",	"physical; of or for the body",
	"correlate",	"have a mutual relation",
	"corroboration",	"additional, strengthening evidence",
	"countenance",	"to favor or approve of",
	"counterfeit",	"forgery",
	"countervail",	"counterbalance",
	"covert",	"disguised",
	"covetous",	"eagerly desirous",
	"cower",	"crouch; shrink back",
	"craven",	"cowardly",
	"crease",	"line made by crushing; white line on the ground in cricket",
	"credulity",	"too great a readiness to believe things",
	"credulous",	"ready to believe things",
	"crush",	"press, lose shape, subdue, overwhelm",
	"cryptic",	"secret, with a hidden meaning",
	"cumbersome",	"burdensome, heavy and awkward to carry",
	"curmudgeon",	"bad-tempered person",
	"curriculum",	"course of study",
	"cursory",	"quick, hurried",
	"curtail",	"make shorter then was planned",
	"cynic",	"person who see no good in anything",
	"dart",	"quick movement; missile in darts",
	"daunt",	"intimidate, make fearful",
	"dawdler",	"person who is slow; waste of time",
	"dearth",	"shortage",
	"debacle",	"a breakup, overthrow, sudden disaster",
	"decorous",	"polite, decent",
	"decorum",	"propriety, properness",
	"decree",	"order given by authority",
	"decry",	"disapprove of",
	"defer",	"postpone; give way (to show respect)",
	"deference",	"respect",
	"deferential",	"showing respect",
	"defiance",	"open disobedience or resistance",
	"deflect",	"turn aside",
	"defy",	"resist openly",
	"degrade",	"reduce in rank or status",
	"delineate",	"to portray, depict, sketch out",
	"deluge",	"great flood, heavy rush of water",
	"demagogue",	"person appealing not to reasons",
	"demur",	"to hesitate, raise objections",
	"denigrate",	"blacken, belittle, sully, defame",
	"denouement",	"an outcome or solution; the unraveling of a plot",
	"denounce",	"give information against",
	"dent",	"hollow, depression mad by a blow",
	"deplete",	"use until none remains",
	"deposition",	"dethronement, depositing",
	"deprave",	"make morally bad; corrupt",
	"deprecate",	"protest against, express disapproval of",
	"dereliction",	"deserting and leaving to fall into ruins",
	"derision",	"ridicule, mockery, deriding",
	"derivative",	"derived, not original or primitive",
	"derivative",	"unoriginal, obtained from another source",
	"derogatory",	"insulting; tending to damage",
	"descry",	"catch sight of, see smth in the distance",
	"desiccant",	"substance used to absorb moisture",
	"desiccate",	"to dry up, dehydrate",
	"desuetude",	"cessation of use; disuse",
	"desultory",	"aimless, haphazard, digressing at random",
	"detach",	"separate",
	"deter",	"discourage, hinder",
	"detraction",	"slandering, verbal attack, aspersion",
	"detumescence",	"diminishing or lessening of swelling",
	"deviance",	"being different in moral standards (from normal)",
	"dexterity",	"skill (esp. in handling)",
	"dexterous",	"clever, skillful with hands",
	"diaphanous",	"transparent, gauzy",
	"diatribe",	"bitter and violent attack in words",
	"dictate",	"order",
	"diffidence",	"shyness",
	"diffident",	"lacking in self-confidence",
	"dilate",	"speak comprehensively, become wider, large",
	"dilatory",	"causing delay, procrastinating",
	"disabuse",	"to undeceive, correct a false impression",
	"disallow",	"refuse to allow or accept as a correct",
	"discern",	"see with an effort but clearly",
	"discomfit",	"confuse, embarrass",
	"discomfit",	"to defeat, put down",
	"disconcert",	"upset the self-possession of",
	"discountenance",	"refuse to approve of",
	"discourse",	"speech, lecture,",
	"discredit",	"refuse to believe",
	"disdain",	"look on with contempt",
	"disencumber",	"free from encumbrance",
	"disheveled",	"untidy",
	"disingenuous",	"sophisticated, artful, trying to deceive, cunning",
	"disinter",	"dig up from the earth",
	"dislodge",	"move, force from the place occupied",
	"dismal",	"sad, gloomy, miserable",
	"disparate",	"essentially different",
	"dispassionate",	"free from passion",
	"dissemble",	"speak or behave so as to hide smth (in mind)",
	"disseminate",	"distribute (esp. ideas)",
	"dissent",	"have a different opinion, refuse to assent",
	"dissipation",	"going away, dispersing",
	"dissolution",	"disintegration, looseness in morals",
	"distinct",	"easily heard, seen, understood, clearly marked",
	"distorted",	"pulled out of the usual shape, give a false account of",
	"distraught",	"distracted, violently upset in mind",
	"distress",	"great pain; cause discomfort",
	"divergence",	"getting farther apart from a point",
	"diverse",	"of different kinds",
	"divestiture",	"taking off, getting rid of, giving up",
	"divulge",	"make known smth secret",
	"doggerel",	"trivial, poorly constructed verse",
	"dogmatic",	"positive, certain, arbitrary, without room for discussion",
	"dogmatism",	"being dogmatic",
	"dolt",	"stupid fellow",
	"dormant",	"in a state of inactivity but awaiting development",
	"dote",	"show much fondness, center one's attention",
	"drone",	"male bee, person who isn't self-employed",
	"drowsiness",	"feeling sleepy, half asleep",
	"dubious",	"feeling doubt",
	"dud",	"no use person, smth that fails",
	"dulcet",	"melodious, harmonious",
	"dupe",	"cheat, make a fool of",
	"duplicity",	"deliberate deception",
	"duress",	"threats to compel smb",
	"dwarf",	"person or smb much below the usual size",
	"dynamo",	"a generator, something that produces electric current",
	"earthenware",	"dishes made of baked clay",
	"ebullience",	"exuberance, outburst of feeling",
	"ebullient",	"overflowing with enthusiasm; showing excitement",
	"ecumenical",	"representing the whole Christian world",
	"edacious",	"voracious, devouring",
	"eddy",	"circular or spiral movement (e.g.. of wind)",
	"effete",	"infertile, worn out, weak",
	"efficacy",	"production of a desired result",
	"effluvia",	"outflow in a stream of particles; a noxious odor or vapor",
	"effrontery",	"boldness, impudence, arrogance",
	"egress",	"way out, exit",
	"elaborate",	"worked out with much care in great detail",
	"elate",	"stimulate",
	"elation",	"high-spirits",
	"electorate",	"all the electors",
	"elegy",	"a lament, a melancholy composition",
	"elicit",	"draw out",
	"eloquence",	"fluent speaking; skillful use of language",
	"emaciate",	"make thin and weak",
	"embellish",	"make beautiful",
	"embezzle",	"use in a wrong way for one's own benefit",
	"emergence",	"emerging",
	"emote",	"stir up, excite",
	"empirical",	"relying on experiment",
	"encapsulate",	"enclose in capsule",
	"encomium",	"warm or glowing praise; eulogy, panegyric",
	"encumbrance",	"burden; things that get on the way of",
	"endearing",	"making dear or liked",
	"endemic",	"epidemic",
	"endemic",	"prevailing in a specific area",
	"endorse",	"write one's name on the back of",
	"enduring",	"lasting",
	"enervate",	"weaken, deprive of strength, attenuate",
	"engender",	"cause, produce, give rise to",
	"engrave",	"impress deeply",
	"engrossing",	"taken up all the time or attention; writing in large or formal",
	"engulf",	"swallow up",
	"enigma",	"smth that is puzzling",
	"enmity",	"hatred; being an enemy",
	"enormity",	"excessive wickedness; evilness",
	"enormousness",	"great size",
	"entangle",	"put into difficulties",
	"entreat",	"ask earnestly",
	"enzyme",	"catalyst",
	"epicure",	"food lover, a connoisseur of food",
	"epicurean",	"devoted to pleasure (sensuous enjoyment)",
	"epistle",	"letter",
	"epithet",	"adjective",
	"epitome",	"brief summary; representative example; a typical model",
	"equable",	"steady, regular",
	"equanimity",	"calmness of temperament",
	"equilibrium",	"state of being balanced",
	"equipoise",	"equal distribution of weight; equilibrium",
	"equivocal",	"having a double or doubtful meaning; suspicious",
	"equivocate",	"try to deceive by equivocal language",
	"eradicate",	"get rid of; pull up by the roots",
	"erasure",	"erasing, removing all traces",
	"erode",	"wear away, eat into",
	"erratic",	"irregular in behaviour or opinion",
	"erudite",	"learned, scholarly",
	"escalate",	"increase, develop",
	"esoteric",	"abstruse; intended only for a small circle of",
	"espouse",	"marry; give one's support to",
	"eulogy",	"formal praise; panegyric",
	"euphoria",	"elation; state of pleasant excitement",
	"euthanasia",	"easy and painless death",
	"evaluating",	"finding out the value",
	"evaporate",	"change into vapor, disappear, die",
	"evince",	"to show clearly, to indicate",
	"evoke",	"call up, bring out",
	"evolve",	"unfold, develop naturally and gradually",
	"excoriate",	"to flay, stip off the skin; to denounce sharply",
	"excoriation",	"severe criticism",
	"exculpate",	"free from blame",
	"exculpate",	"to clear from a charge of guilt",
	"exert",	"but forth; bring into use",
	"exertion",	"instance of exerting",
	"exhaustive",	"complete, thorough",
	"exigency",	"emergency, an urgent situation",
	"exonerate",	"free; clear",
	"exoneration",	"set smb clear, free (e.g.. from blame)",
	"exorbitant",	"much too high or great",
	"expatiate",	"to roam, wander freely",
	"expedient",	"likely to be useful for a purpose",
	"expiation",	"ending; expiring",
	"exploit",	"brilliant achievement; develop; use selfishly",
	"expostulate",	"argue earnestly to dissuade, correct, or protest",
	"expurgate",	"to remove obscenity, purify, censor",
	"exscind",	"to cut out, cut away",
	"exsert",	"thrust out, push forth",
	"extant",	"still in existence",
	"extensive",	"far-reaching",
	"extenuate",	"reduce the strength of, lessen seriousness, partially excuse",
	"extinct",	"no longer active",
	"extirpate",	"to destroy, exterminate, cut out, exscind",
	"extol",	"praise highly",
	"extort",	"obtain by threats, violence",
	"extralegal",	"outside the law",
	"extricable",	"that can be freed",
	"extrovert",	"cheerful person",
	"exuberance",	"state of growing vigorously; being full of life",
	"facetious",	"humorous, funny, jocular",
	"facile",	"easily done",
	"facilitate",	"make easy (e.g.. a process of smth)",
	"fallacious",	"based on error",
	"fallacy",	"false or mistaken belief",
	"fatuous",	"without sense, foolish self-satisfaction",
	"faucet",	"device for controlling the outflow of a liquid",
	"fawn",	"young deer, try to win smb's favor",
	"feckless",	"futile, irresponsible, inefficient",
	"feckless",	"lacking purpose or vitality; ineffective; careless",
	"fecund",	"fertile",
	"feint",	"pretend",
	"felicitous",	"apt; suitably expressed, well chosen, apropos",
	"felon",	"person guilty of murder",
	"ferment",	"substance; become excited",
	"ferocity",	"savage cruelty",
	"ferret",	"discover by searching; search",
	"fertile",	"producing much, full of ideas",
	"fertilize",	"make fertile or productive",
	"fervid",	"intense, zealous",
	"fervid",	"showing earnest feeling",
	"fervor",	"warmth of feelings; earnestness",
	"fetter",	"to shackle, put in chains",
	"feud",	"bitter quarrel over a long period of time",
	"fidelity",	"loyalty, accuracy",
	"fidget",	"move restlessly, make nervous",
	"figurehead",	"carved image on the prow of a ship",
	"finesse",	"delicate way of dealing with a situation",
	"finical",	"too fussy about food, clothing, etc.",
	"finicky",	"finical",
	"finite",	"limited, having bounds",
	"fission",	"splitting or division (esp. of cells)",
	"fixate",	"stare at",
	"flamboyant",	"brightly colored, florid",
	"flammable",	"having tendency to burst into flames",
	"flaunting",	"show off complacently",
	"flaw",	"crack, lessen value",
	"flax",	"pale yellow (hair); a plant",
	"fledged",	"able to fly, trained, experienced",
	"fleet",	"number of ships, quick-moving",
	"fleeting",	"passing quickly",
	"flexibility",	"easily bent without braking",
	"flinch",	"draw, move back, wince",
	"florid",	"very much ornamented; naturally red (e.g.. of face)",
	"floridness",	"ruddiness; heavily decorated; ornateness",
	"flout",	"reject, mock, to go against (as in going against tradition)",
	"fluster",	"make nervous or confused",
	"foible",	"defect of character (a person is wrongly proud)",
	"foil",	"prevent from carrying out; contrast",
	"foment",	"put smth warm (to lessen the pain)",
	"foppish",	"like a man who pays too much attention to his clothes",
	"forbear",	"refrain from, be patient; ancestor",
	"forbearance",	"patience, willingness to wait",
	"ford",	"shallow place in a river (to cross)",
	"forestall",	"prevent by taking action in advance, preempt",
	"forfeit",	"suffer the loss of smth",
	"forge",	"workshop for the shaping of metal; to shape metal; lead",
	"forgery",	"counterfeit",
	"forswear",	"renounce, disallow, repudiate",
	"fortify",	"strengthen",
	"fortuitous",	"happening by chance",
	"foster",	"nurture, care for",
	"fragile",	"easily injured, broken or destroyed",
	"fragrant",	"sweet-smelling",
	"franchise",	"special right given by authority",
	"frantic",	"wildly excited with joy, pain, anxiety",
	"frenetic",	"frantic, frenzied",
	"fret",	"worry; irritation; wear away",
	"friction",	"the rubbing of one thing against another, difference of opinion",
	"fringe",	"edge; ornamental border; part of hair over the forehead",
	"froward",	"intractable, not willing to yield or comply, stubborn",
	"frugal",	"careful, economical",
	"fulminate",	"berate, vituperate, to thunder out, to explode",
	"fulmination",	"bitter protest",
	"fulsome",	"disgusting, offensive due to excessiveness",
	"gainsay",	"to deny, declare false, to oppose",
	"gambol",	"quick, playful jumping",
	"garment",	"article of clothing",
	"garner",	"to gather and save; to store up",
	"garrulity",	"talkativeness",
	"garrulous",	"too talkative",
	"gaucherie",	"socially awkward, tactless behavior",
	"germane",	"relevant; pertinent to",
	"gist",	"the point, general sense",
	"glean",	"gather facts in small quantities",
	"glib",	"ready and smooth but not sincere",
	"gloat",	"over look at with selfish delight",
	"glut",	"supply to much, fill to excess",
	"gnaw",	"waste away; bite steadily",
	"goad",	"smth urging a person to action",
	"gossamer",	"soft, light, delicate material",
	"gouge",	"tool for cutting grooves in wood",
	"grace",	"favor",
	"grave",	"serious, requiring consideration",
	"gregarious",	"living in societies; liking the company",
	"grievance",	"cause for complaint or protest",
	"grievous",	"causing grief or pain; serious, dire, grave",
	"grimace",	"twisted expression of a face",
	"grind",	"crush, polish",
	"grooves",	"long channel in the surface, habitual way of living",
	"grovel",	"crawl, humble oneself",
	"guile",	"deceit, cunning",
	"guileless",	"straight-forward, candid",
	"gull",	"cheat, deceive",
	"gullible",	"easily gulled",
	"gust",	"outburst of feeling; sudden rain, wind, fire, etc.",
	"hack",	"cut roughly; hired horse",
	"hallow",	"to make holy; consecrate",
	"hamper",	"basket with a lid, prevent free movement or activity",
	"hapless",	"unlucky, unfortunate",
	"harangue",	"a long, passionate speech",
	"harbinger",	"smth or smb that foretells the coming of",
	"harrow",	"to distress, create stress or torment",
	"harsh",	"rough, cruel, stern",
	"haughty",	"arrogant; conceited",
	"haven",	"harbor, safety place",
	"heed",	"pay attention; notice",
	"heinous",	"odious (of crime)",
	"heresy",	"belief contrary to what is generally accepted",
	"hermetic",	"sealed by fusion",
	"heterogeneous",	"made up of different kinds",
	"hew",	"make by hard work; cut (by striking)",
	"hirsute",	"hairy, shaggy",
	"hoax",	"mischievous trick played on smb for a joke",
	"hoi polloi",	"the masses; the rabble",
	"hollow",	"not soled, with hole",
	"holster",	"leather case for a pistol",
	"hone",	"stone used for sharpening tools",
	"hoodwink",	"trick, mislead",
	"hospitable",	"liking to give hospitality",
	"hubris",	"arrogant pride",
	"hurdle",	"light frame, fence to be jumped over",
	"husk",	"worthless outside part of anything",
	"hypocrisy",	"falsely making oneself appear to be good",
	"iconoclast",	"person who attacks popular beliefs",
	"iconoclastic",	"attacking cherished beliefs",
	"idiosyncrasy",	"personal mannerism",
	"idolatrous",	"worshipping idols",
	"idolatry",	"excessive admiration of",
	"idyll",	"a carefree episode or experience",
	"ignoble",	"dishonorable, common, undignified",
	"ignominious",	"shameful, dishonorable, undignified, disgraceful",
	"illicit",	"unlawful, forbidden",
	"illusory",	"deceptive; an illusion",
	"imbroglio",	"complicated and embarrassing situation",
	"immaculate",	"pure, faultless",
	"immerse",	"absorb; put under the surface of",
	"imminent",	"likely to come or happen soon",
	"immutable",	"that cannot be changed",
	"impair",	"worsen, diminish in value",
	"impaired",	"damaged, weakened",
	"impassive",	"unmoved; feeling no sign of passion",
	"impecunious",	"having little or no money",
	"impede",	"hinder; get in the way of",
	"impediment",	"smth that hinders (e.g. stammer)",
	"impending",	"imminent, being about to happen, expected",
	"imperative",	"urgent, essential",
	"imperious",	"commanding, haughty, arrogant",
	"imperviousness",	"haughty, arrogant, commanding",
	"impermeable",	"that cannot be permeated",
	"imperturbable",	"calm; not capable of being excited",
	"impervious",	"not allowing to pass through (of materials)",
	"imperviousness",	"arrogance, commanding presence, overbearingness",
	"impetuous",	"having sudden energy, impulsive, thrusting ahead, forceful",
	"impiety",	"lack of reverence or dutifulness",
	"implacable",	"incapable of being placated, unpleasable",
	"implausibility",	"incredibility",
	"implicate",	"show that smb has a share",
	"implicit",	"implied though not plainly expressed",
	"implosion",	"collapse; bursting inward",
	"imply",	"make a suggestion",
	"importune",	"beg urgently; solicit (of a prostitute)",
	"imprecation",	"an invocation of evil; a curse",
	"impromptu",	"without preparation",
	"impudence",	"being rash, indiscreet",
	"impudent",	"rash, indiscreet",
	"impugned",	"challenged, to be doubted",
	"impute",	"to attribute to a cause or source, ascribe",
	"inadvertent",	"not paying proper attention",
	"inane",	"silly, senseless",
	"inasmuch",	"since, because",
	"incense",	"make angry",
	"incessant",	"often repeated, continual",
	"inchoate",	"not yet fully formed, rudimentary, elementary",
	"incise",	"engrave, make a cut in",
	"incite",	"stir up, rouse",
	"inclined",	"directing the mind in a certain direction",
	"incoherently",	"not consistently, unclearly",
	"incongruous",	"out of place, not in harmony or agreement",
	"incorrigibility",	"cannot be cured or corrected",
	"incredulous",	"skeptical, unwilling to believe",
	"inculcate",	"fix firmly by repetition",
	"incumbents",	"official duties",
	"incursion",	"a raid, a sudden attack",
	"indefatigability",	"not easily exhaustible; tirelessness",
	"indelible",	"that cannot be rubbed out",
	"indelicate",	"immodest; lacking in refinement",
	"indigence",	"poverty",
	"indigenous",	"native",
	"indistinct",	"not easily heard, seen, clearly marked",
	"indolence",	"laziness",
	"indomitable",	"not easily discouraged or subdued",
	"indulge",	"gratify, give way to, satisfy; allow oneself",
	"indulgent",	"inclined to indulge",
	"ineffable",	"to great to be described in words",
	"ineluctable",	"certain, inevitable",
	"inept",	"unskillful; said or done at the wrong time",
	"infertile",	"not fertile, barren",
	"inflame",	"become red, angry",
	"inflammatory",	"tending to inflame",
	"infuriate",	"fill with fury or rage",
	"infuse",	"put, pour, fill",
	"ingenuous",	"naive, young, artless, frank, honest, sincere",
	"ingest",	"take in by swallowing",
	"inherent",	"existing as a natural part",
	"inhibit",	"hinder, restrain",
	"inimical",	"harmful or friendly",
	"inimitable",	"defying imitation, unmatchable",
	"innocuous",	"causing no harm",
	"inscrutable",	"incapable of being discovered or understood",
	"insensible",	"unconscious, unresponsive, unaffected",
	"insinuate",	"suggest unpleasantly; make a way for smth gently",
	"insipid",	"without taste or flavor",
	"insouciant",	"unconcerned, carefree",
	"insularity",	"narrow-mindedness, isolated",
	"insurrection",	"rising of people to open resistance to",
	"interdict",	"prohibit, forbid",
	"interim",	"as an installment",
	"intersperse",	"place here and there",
	"intervene",	"come between; interfere to change the result",
	"intractable",	"unruly, refractory, stubborn",
	"intransigence",	"unwillingness to compromise, stubbornness, intractability",
	"intransigent",	"uncompromising",
	"intrepid",	"fearless, brave, undaunted",
	"introspection",	"examining one's own thoughts and feelings",
	"inundate",	"flood; cover by overflowing",
	"inured",	"accustomed to, adapted",
	"invective",	"abusive language, curses",
	"inveigh",	"to attack verbally, denounce, deprecate",
	"inveterate",	"deep-rooted. long-established",
	"involute",	"complex",
	"irascible",	"irritable, easily angered",
	"irate",	"angry",
	"ire",	"anger",
	"irksome",	"tiresome",
	"irrelevant",	"not relevant, not connected",
	"irresolute",	"hesitating; undecided",
	"irrevocable",	"final and unalterable",
	"itinerary",	"plan for a journey, details or records of a route",
	"itinerate",	"to travel from place to place, to peregrinate",
	"jabber",	"talk excitedly; utter rapidly",
	"jeopardize",	"put in danger",
	"jibe",	"gibe, make fun of",
	"jocular",	"meant as a joke",
	"judicious",	"sound in judgment; wise",
	"knit",	"draw together, unite firmly",
	"labyrinthine",	"to entangle the state of affairs",
	"lachrymose",	"causing tears, tearful",
	"lackluster",	"(of eyes) dull",
	"laconic",	"brief, to the point, terse",
	"lag",	"go too slow",
	"lament",	"show, feel great sorrow",
	"lassitude",	"weariness, tiredness",
	"latent",	"present but not yet active, developed or visible",
	"laudatory",	"expressing or giving praise",
	"lavish",	"giving or producing freely, liberally or generously",
	"leakage",	"the process of leaking",
	"legacy",	"smth handed down from ancestors",
	"libel",	"statement that damages reputation",
	"liberality",	"free giving; generosity",
	"libertine",	"immoral person",
	"lien",	"legal claim until a debt on it is repaid",
	"limn",	"paint, portray",
	"limp",	"lacking strength, walking unevenly",
	"lithe",	"bending, twisting",
	"loll",	"rest, to sit or stand in a lazy way; hang (dog's tongue)",
	"loquacious",	"talkative, garrulous",
	"lubricant",	"substance that makes work easier",
	"lubricate",	"put oil to make work easily",
	"lubricious",	"lewd, wanton, greasy, slippery",
	"lucubrate",	"write in scholarly fashion",
	"luculent",	"easily understood, lucid, clear",
	"lugubrious",	"mournful, excessively sad",
	"lull",	"become quiet or less active",
	"luminary",	"star, light-giving body",
	"lustrous",	"being bright, polished",
	"macabre",	"gruesome, suggesting death",
	"machination",	"plot, scheme (esp. evil)",
	"maladroit",	"tactless, clumsy",
	"malapropism",	"misuse of a word (for one that resembles it)",
	"malevolence",	"wishing to do evil",
	"malign",	"injurious, speak ill of smb, tell lie",
	"malinger",	"to fake illness or injury, in order to shirk a duty",
	"malleable",	"yielding; easily shaped; moldable; adapting",
	"manacle",	"chains for the hands or feet",
	"martial",	"brave, of associated with war",
	"massacre",	"cruel killing of a large number of people",
	"matriculation",	"be admitted, enter a university as a student",
	"mature",	"come to full development, to a state ready for use",
	"maudlin",	"sentimental in a silly or tearful way",
	"maverick",	"rebel, nonconformist",
	"mellifluous",	"sweetly flowing",
	"mendacious",	"false",
	"mendacity",	"dishonesty",
	"mendicant",	"a beggar",
	"mercurial",	"quick, changeable in character, fleeting",
	"meretricious",	"attractive on the surface but of little value",
	"mesmerize",	"hypnotize",
	"meticulous",	"giving great attention to details",
	"mettle",	"quality of endurance or courage",
	"mettlesome",	"courageous, high-spirited",
	"middling",	"fairly good but not very good",
	"minatory",	"menacing, threatening",
	"mince",	"pronounce or speak affectedly, euphemize",
	"misanthrope",	"person who hates mankind",
	"mischievous",	"harmful, causing mischief",
	"miser",	"person who loves wealth and spends little",
	"misogynist",	"one who hates women/females",
	"missile",	"smth that is thrown or shot",
	"mitigate",	"make less severe or painful",
	"moderation",	"quality of being limited, not extreme",
	"mollify",	"make calmer or quieter",
	"molt",	"moult, lose hair, feathers before new growing",
	"morbid",	"diseased, unhealthy (e.g.. about ideas)",
	"morose",	"ill-tempered, unsocial",
	"mortuary",	"place where dead bodies are taken to be kept until burial",
	"multifarious",	"varied, motley, greatly diversified",
	"mundane",	"worldly as opposed to spiritual; commonplace, everyday",
	"myriad",	"very great number",
	"nadir",	"lowest, weakest point",
	"nascent",	"coming into existence, emerging",
	"nebulous",	"cloud-like; hazy; vague; indistinct",
	"negligent",	"taking too little care",
	"neophyte",	"person who has been converted to a belief",
	"nexus",	"a connection, tie, or link",
	"nibble",	"show some inclination to accept (an offer)",
	"nice",	"precise, sensitive to subtleness",
	"noisome",	"offensive, disgusting (smell)",
	"nonchalant",	"not having interest",
	"nonplused",	"greatly surprised",
	"nostrum",	"a quack remedy, an untested cure",
	"notion",	"nominal, token",
	"noxious",	"harmful",
	"nullify",	"make void and null",
	"numb",	"without ability to feel or move",
	"numbness",	"without ability to move a finger",
	"obdurate",	"hardened and unrepenting; stubborn, inflexible",
	"obfuscate",	"to darken, make obscure, muddle",
	"oblivious",	"unaware, having no memory",
	"obloquy",	"abusively detractive language, sharp criticism, vituperation",
	"obsequious",	"too eager to obey or serve",
	"obsolete",	"no longer used",
	"obstreperous",	"noisy, loud",
	"obtain",	"to be established, accepted, or customary",
	"obtrusive",	"projecting, prominent, undesirably noticeable",
	"obviate",	"to make unnecessary, get rid of",
	"occluded",	"blocked up",
	"occult",	"hidden, concealed, beyond comprehension",
	"odious",	"repulsive, hateful",
	"odium",	"contempt, dislike, aversion",
	"odor",	"smell; favor; reputation",
	"officious",	"too eager or ready to help, offer advice",
	"onerous",	"needing effort, burdensome",
	"opprobrious",	"showing scorn or reproach",
	"ossify",	"to turn to bone; to settle rigidly into an idea",
	"ostensible",	"seeming, appearing as such, professed",
	"ostentation",	"display to obtain admiration or envy",
	"ostentatious",	"fond of showing ostentation",
	"ostracism",	"shut out from society, refuse to meet, talk",
	"ostrich",	"fast-running bird unable to fly",
	"outset",	"start",
	"overhaul",	"examine thoroughly to learn about the condition",
	"overweening",	"presumptuously arrogant, overbearing, immoderate, being a jerk",
	"overwhelm",	"weigh down, submerge",
	"paean",	"song of praise or triumph",
	"palate",	"roof of the mouth; sense of taste",
	"palatial",	"magnificent",
	"palliate",	"lessen the severity of",
	"palliate",	"to make something appear less serious, to alleviate, to gloss over",
	"palpability",	"can be felt, touched, understood",
	"palpitate",	"tremble, beat rapidly and irregularly",
	"panegyric",	"formal praise, eulogy",
	"paradigm",	"a model, example, or pattern",
	"parenthesis",	"sentence within another one, smth separated",
	"pariah",	"an outcast, a rejected and despised person",
	"parsimonious",	"too economical, miserly",
	"partisan",	"one-sided, committed to a party, biased or prejudiced",
	"patron",	"regular customer; person who gives support",
	"paucity",	"scarcity, a lacking of",
	"peccadillo",	"small sin; small weakness in one's character",
	"pedantic",	"bookish, showing off learning",
	"pedestrian",	"commonplace, trite, unremarkable",
	"pellucid",	"transparent, easy to understand",
	"penchant",	"strong inclination, a liking",
	"penitent",	"feeling or showing regret",
	"penury",	"extreme poverty",
	"peregrination",	"traveling about, wandering",
	"peremptory",	"urgent, imperative, unchallengeable, ending debate",
	"perennial",	"lasting for a long time (e.g.. a year)",
	"perfidious",	"treacherous, faithless",
	"perfidy",	"treachery; breaking of faith",
	"perfunctory",	"done as a duty without care",
	"perilous",	"dangerous",
	"peripatetic",	"wandering",
	"perish",	"be destroyed; decay",
	"perjury",	"willful false statement, unlawful act",
	"permeate",	"spread into every part of",
	"pernicious",	"harmful, injurious",
	"perpetrate",	"be guilty; commit (a crime)",
	"persevere",	"keep on steadily, continue",
	"personable",	"pleasing in appearance, attractive",
	"perspicacity",	"quick judging and understanding",
	"pertain",	"belong as a part, have reference",
	"pest",	"destructive thing or a person who is nuisance",
	"petrified",	"taken away power (to think, feel, act)",
	"petrify",	"to make hard, rocklike",
	"petrous",	"like a rock, hard, stony",
	"petulant",	"unreasonably impatient",
	"philistine",	"a smug ignorant person; one who lacks knowledge",
	"phlegmatic",	"calm, sluggish temperament; unemotional",
	"picaresque",	"involving clever rogues or adventurers",
	"pied",	"of mixed colors",
	"pinch",	"be too tight, take between the thumb and finger",
	"pious",	"dutiful to parents; devoted to religion",
	"piquant",	"agreeably pungent, stimulating",
	"pique",	"hurt the pride or self-respect, stir (curiosity)",
	"pitfall",	"covered hole as a trap, unsuspected danger",
	"pith",	"essential part, force, soft liquid substance",
	"pivotal",	"of great importance (others depend on it)",
	"placate",	"soothe, pacify, calm",
	"plaintive",	"mournful, melancholy, sorrowful",
	"plaque",	"flat metal on a wall as a memorial",
	"platitude",	"a trite or banal statement; unoriginality",
	"plea",	"request",
	"plead",	"address a court of law as an advocate",
	"plethora",	"glut",
	"pliant",	"pliable, easily bent, shaped or twisted",
	"plod",	"continue doing smth without resting",
	"pluck",	"pull the feathers off, pick (e.g.. flowers)",
	"plumb",	"get to the root of",
	"plummet",	"fall, plunge, steeply",
	"plunge",	"move quickly, suddenly and with force",
	"poignant",	"deeply moving; keen",
	"poise",	"be ready, be balanced, self-possession",
	"polemical",	"controversial, argued",
	"ponderous",	"heavy, bulky, dull",
	"portent",	"omen; marvelous; threatening",
	"poseur",	"someone taking on airs to impress others; a phony",
	"posture",	"state, attitude; adopt a vain",
	"poverty",	"state of being poor",
	"pragmatic",	"practical, favoring utility",
	"precarious",	"uncertain, risky, dangerous",
	"precept",	"moral instruction",
	"precepts",	"rules establishing standards of conduct",
	"precipitate",	"throw smth violently down from a height",
	"preclude",	"prevent, make impossible",
	"precursory",	"preliminary, anticipating",
	"predilection",	"special liking, mental preference",
	"predominate",	"have more power than others",
	"preempt",	"obtain by preemption or in advance",
	"premature",	"doing or happening smth before the right time",
	"preponderance",	"greatness in number, strength, weight",
	"presage",	"warning sign",
	"preternatural",	"not normal or usual",
	"prevalent",	"common",
	"prevaricate",	"to equivocate, to stray from the truth",
	"prim",	"neat; formal",
	"pristine",	"primitive, unspoiled, pure, as in earlier times, unadulterated",
	"probity",	"uprightness, incorruptibility, principle",
	"proclivity",	"inclination",
	"procrastination",	"keeping on putting off",
	"prodigal",	"wasteful, reckless with money",
	"prodigious",	"enormous, wonderful",
	"profane",	"worldly, having contempt for God",
	"profligate",	"wasteful, prodigal, licentious, extravagant",
	"profundity",	"depth",
	"proliferate",	"grow, reproduce by rapid multification",
	"prolix",	"tiring because too long",
	"prone",	"prostrate; inclined to (undesirable things)",
	"propagation",	"increasing the number, spreading, extending",
	"propinquity",	"nearness in time or place, affinity of nature",
	"propitiate",	"do smth to take away the anger of",
	"propitiatory",	"conciliatory, appeasing, mitigating",
	"propitious",	"auspicious, presenting favorable circumstances",
	"prosaic",	"everyday, mundane, commonplace, trite, pedestrian",
	"proscribe",	"denounce as dangerous",
	"protracted",	"prolonged",
	"provident",	"frugal; looking to the future",
	"provisional",	"of the present time only",
	"provoke",	"make angry; vax",
	"prudence",	"careful forethought",
	"prudish",	"easily shocked, excessively modest",
	"prune",	"dried plum, silly person",
	"pry",	"get smth; inquire too curiously",
	"pugnacious",	"fond of, in the habit of fighting",
	"punch",	"strike with the fist; tool for cutting holes; alc. drink",
	"punctilious",	"precise, paying attention to trivialities",
	"pundit",	"pedant, authority on a subject",
	"pungency",	"sharpness; stinging quality",
	"purvey",	"provide, supply",
	"pusillanimous",	"cowardly, craven",
	"pyre",	"large pile of wood for burning",
	"quack",	"person dishonestly claiming to smth",
	"quaff",	"drink deeply",
	"quail",	"lose courage, turn frightened",
	"qualm",	"feeling of doubt, temporary feeling of sickness",
	"quell",	"suppress, subdue",
	"quibble",	"try to avoid by sophistication",
	"quiescent",	"at rest, dormant, torpid",
	"quirk",	"habit or action peculiar to smb or smth",
	"quixotic",	"generous, unselfish",
	"quotidian",	"banal; everyday",
	"rabble",	"mob, crowd; the lower classes of populace",
	"raconteur",	"person who tells anecdotes",
	"radiant",	"bright, shining",
	"raffish",	"low, vulgar, base, tawdry",
	"rail",	"at find fault, utter reproaches",
	"ramify",	"to be divided or subdivided; to branch out",
	"rancorous",	"feeling bitterness, spitefulness",
	"rant",	"use extravagant language",
	"rapacious",	"greedy (esp for money)",
	"rarefy",	"to make thin, to make less dense, to purify or refine",
	"reactionary",	"opposing progress",
	"rebuff",	"snub",
	"recalcitrant",	"disobedient",
	"recant",	"take back as being false; give up",
	"recast",	"cast or fashion anew",
	"recidivism",	"relapse into antisocial or criminal behavior",
	"reciprocity",	"granting of privileges in return for similar",
	"recitals",	"a number of, performance of music",
	"recluse",	"person who lives alone and avoids people",
	"recompense",	"make payment to; reward, punish",
	"reconcile",	"settle a quarrel; restore peace",
	"recondite",	"little known; abstruse",
	"recourse",	"smth turned to for help",
	"recreancy",	"cowardice, a cowardly giving up",
	"recuperate",	"become strong after illness, loss, exhaustion",
	"redeem",	"get back by payment; compensate",
	"redemptive",	"serving to redeem",
	"redoubtable",	"formidable, causing fear",
	"refine",	"make or become pure, cultural",
	"refractory",	"stubborn, unmanageable, untractable",
	"refulgent",	"shining, brilliant",
	"regale",	"to delight or entertain; to feast",
	"regicide",	"crime of killing a king",
	"reiterate",	"say or do again several times",
	"rejuvenation",	"becoming young in nature or appearance",
	"relapse",	"fall back again",
	"relinquish",	"give up",
	"reluctant",	"unwilling or disinclined",
	"remonstrate",	"to protest, object",
	"render",	"deliver, provide, represent",
	"renovate",	"restore smth to better condition",
	"renowned",	"celebrated, famous",
	"rent",	"regular payment for the use of smth, division or split",
	"repast",	"meal",
	"repine",	"at be discontented with",
	"reproach",	"scold, upbraid",
	"reprobate",	"person hardened in sin; one devoid of decency",
	"repudiate",	"disown, refuse to accept or pay",
	"repulsive",	"causing a feeling of disgust",
	"requite",	"repay, give in return",
	"resigned",	"unresisting, submissive",
	"resilience",	"quality of quickly recovering the original shape",
	"resolve",	"determine",
	"resort",	"to frequently visit",
	"restive",	"refusing to move; reluctant to be controlled",
	"resurrect",	"bring back into use",
	"resuscitation",	"coming back to consciousness",
	"retard",	"check, hinder",
	"reticent",	"reserved, untalkative, silent, taciturn",
	"revere",	"have deep respect for",
	"rift",	"split, crack, dissension",
	"rivet",	"fix, take up, secure; metal pin",
	"roll",	"call calling of names",
	"rope",	"thick strong cord made by twisting",
	"rotund",	"rich and deep; plump and round",
	"rubric",	"heading, title, or category",
	"ruffian",	"violent, cruel man",
	"sagacious",	"having sound judgment; perceptive, wise; like a sage",
	"salacious",	"obscene",
	"salient",	"prominent, protruding, conspicuous, highly relevant",
	"salubrious",	"healthful",
	"salutary",	"remedial, wholesome, causing improvement",
	"sanctimony",	"self-righteousness, hypocritical, with false piety",
	"sanction",	"approval (by authority); penalty",
	"sanguine",	"cheerful, confident, optimistic",
	"sanity",	"health of mind; soundness of judgement",
	"sap",	"weaken",
	"sate",	"satiate",
	"satiate",	"satisfy fully",
	"saturnine",	"gloomy, dark, sullen, morose",
	"savant",	"person of great learning",
	"savor",	"taste, flavor smth",
	"sawdust",	"tiny bits of wood",
	"scabbard",	"sheath for the blade",
	"scent",	"smell (esp pleasant)",
	"scribble",	"write hastily",
	"scurvy",	"mean, contemptible",
	"seal",	"piece of wax, lead, etc stamped on the document",
	"secular",	"material (not spiritual); living outside monasteries",
	"sedulous",	"persevering",
	"seminal",	"like a seed; constituting a source, originative",
	"sententious",	"short and pithy, full of maxims/proverbs",
	"sequence",	"succession, connected line of",
	"serrated",	"having a toothed edge",
	"serration",	"having a toothed edge",
	"servile",	"like a slave, lacking independence",
	"severance",	"severing",
	"shaft",	"arrow or spear, smth long and narrow",
	"shallow",	"little depth; not earnest",
	"shard",	"piece of broken earthenware",
	"sheath",	"cover for the blade of a weapon or a tool",
	"shove",	"push",
	"shrewd",	"astute; showing sound judgement",
	"shrill",	"sharp, piercing",
	"shun",	"keep away from; avoid",
	"shunt",	"send from one track to another; lay aside; evade discussion",
	"sidestep",	"step to one side",
	"sinuous",	"winding, undulating, serpentine",
	"skiff",	"small boat",
	"skit",	"short piece of humorous writing",
	"slack",	"sluggish; dull; not tight",
	"slake",	"to assuage, to satisfy, allay",
	"slate",	"king of blue-grey stone; propose; criticize",
	"sluggard",	"lazy, slow-moving person",
	"soar",	"rise, fly high",
	"sober",	"self-controlled",
	"sobriety",	"quality or condition of being sober",
	"sodden",	"soaked, saturated",
	"soggy",	"heavy with water",
	"solvent",	"of the power of forming a solution",
	"somatic",	"of the body",
	"soot",	"black powder in smoke",
	"sophisticated",	"complex, subtle, refined",
	"sophistry",	"fallacious reasoning, faulty logic",
	"sophomoric",	"self-assured though immature, affected, bombastic, overblown",
	"sordid",	"wretched, comfortless, contemptible",
	"spear",	"weapon with a metal point on a long shaft",
	"specious",	"illogical, of questionable truth or merit",
	"splenetic",	"bad-tempered, irritable",
	"splice",	"join (two ends)",
	"sponge",	"porous rubber for washing; live at once expense",
	"spurious",	"false, counterfeit",
	"spurn",	"have nothing to do; reject or refuse",
	"squalid",	"foul, filthy",
	"squander",	"spend wastefully",
	"stanch",	"to stop the flow of a fluid",
	"steeply",	"rising or falling sharply",
	"stentorian",	"extremely loud and powerful",
	"stickler",	"person who insists on importance of smth",
	"stigma",	"mark of shame or disgrace",
	"stigmatize",	"describe smb scornfully",
	"sting",	"smth sharp",
	"stingy",	"spending, using unwillingly",
	"stint",	"to be thrifty, to set limits",
	"stipulate",	"state or put forward as a necessary condition",
	"stolid",	"showing no emotion; impassive",
	"strands",	"smth twisted together into a rope, line of development",
	"stray",	"wander, lose one's way",
	"streak",	"long, thin; move very fast",
	"striated",	"striped, grooved, or banded",
	"stride",	"walk with long steps",
	"strut",	"a supporting bar",
	"stygian",	"hence, dark, gloomy",
	"stymie",	"to hinder, obstruct, or block",
	"subdue",	"overcome, bring under control",
	"sublime",	"extreme; astounding",
	"submerge",	"put under water, liquid, sink out of sight",
	"suborn",	"induce by bribery or smth to commit perjury",
	"subpoena",	"written order requiring a person to appear in a low court",
	"subsume",	"include under a rule",
	"succor",	"assistance, relief in time of distress",
	"suffice",	"be enough",
	"sullied",	"to be stained or discredited",
	"summarily",	"briefly; without delay",
	"sumptuous",	"magnificent",
	"sundry",	"various, miscellaneous, separate",
	"supercilious",	"disdainful; characterized by haughty scorn",
	"superfluous",	"more then is needed or wanted",
	"superimpose",	"put smth on the top",
	"supersede",	"take the place of",
	"supine",	"lying on the back; slow to act, passive",
	"suppliant",	"asking humbly, beseeching",
	"supplicate",	"make a humble petition to",
	"suppress",	"prevent from being known; put an end to",
	"surfeit",	"satiate, feed to fulness or to excess",
	"susceptibility",	"sensitiveness",
	"sustain",	"keep from falling; maintain; suffer; give a decision",
	"sycophant",	"person who flatter to the rich and powerful",
	"synopsis",	"summary or outline",
	"taciturn",	"untalkative, silent",
	"talon",	"claw of a bird of prey",
	"tamp",	"tap or drive down by repeated light blows",
	"tamper",	"interfere with",
	"tangential",	"suddenly changeable",
	"tarnished",	"lost brightness",
	"taunt",	"contemptuous reproach, hurtful remark",
	"taut",	"tightly stretched",
	"tautology",	"a repetition, a redundancy",
	"tawdry",	"cheap, gaudy, showy, tacky",
	"tease",	"annoy; puzzling question",
	"tedious",	"tiresome",
	"teetotal",	"oppose to alcohol",
	"temerity",	"boldness, brashness, intrepidness",
	"temperance",	"abstinence from alcohol, self-control, moderation",
	"temperate",	"showing self-control",
	"tenacity",	"firmness, persistency, adhesiveness, tending to hang on",
	"tenuous",	"insubstantial, flimsy, weak",
	"terse",	"brief and to the point",
	"thrift",	"care, economy, thriving, prosperous",
	"timid",	"shy, easily frightened",
	"timorous",	"fearful, timid, afraid",
	"tolerable",	"fairly good",
	"tonic",	"smth giving strength or energy",
	"topple",	"be unsteady and overturn",
	"torment",	"severe pain or suffering",
	"torpid",	"sleeping, sluggish, lethargic, dormant",
	"tortuous",	"full of twists and bends",
	"tout",	"person who worries others to buy smth, to use his service",
	"touting",	"act as tout",
	"toy",	"think not seriously, handle absent-mindedly",
	"tractable",	"easily controlled or guided",
	"transgress",	"break, go beyond (a limit)",
	"transient",	"temporary, fleeting",
	"transitory",	"brief",
	"trenchant",	"forceful, effective, vigorous; extremely perceptive, incisive",
	"trend",	"tendency, general direction",
	"trepidation",	"alarm, excited state of mind",
	"trifling",	"unimportant",
	"trite",	"not new",
	"truculence",	"aggressiveness, ferocity",
	"trudge",	"walk heavily",
	"turbid",	"muddy, having the sediment stirred up",
	"turbulence",	"being uncontrolled, violent",
	"turgid",	"excessively ornate; swollen or bloated",
	"turmoil",	"trouble, disturbance",
	"turpitude",	"wickedness, shamefulness",
	"tyro",	"tiro, beginner",
	"ulterior",	"situated beyond",
	"umbrage",	"offense, resentment",
	"uncouth",	"rough, awkward",
	"underbid",	"make a lower bid then smb else",
	"undermine",	"weaken gradually, at the base, make smth under",
	"undulate",	"to move in wavelike fashion, fluctuate",
	"unencumbered",	"easy-going, trifle",
	"unfeigned",	"not pretended, sincere",
	"unscathed",	"unharmed, unhurt",
	"untoward",	"unfortunate, inconvenient",
	"upbraid",	"scold, reproach",
	"urbane",	"elegant, refined in manners",
	"vacillation",	"being uncertain, hesitating",
	"vagary",	"strange act or idea",
	"vain",	"without use, result; conceited",
	"valiant",	"brave",
	"valorous",	"brave",
	"vanquish",	"conquer",
	"vapor",	"stim, mist",
	"veer",	"change direction",
	"venal",	"ready to do smth dishonest",
	"veneer",	"surface appearance covering the true nature",
	"veneration",	"regard with deep respect",
	"veracity",	"truth",
	"verisimilitude",	"appearing true or real",
	"veritable",	"real, rightly named",
	"verve",	"spirit, vigor, enthusiasm",
	"vex",	"annoy, distress, trouble",
	"vigilance",	"watchfulness, self-appointed group who maintain order",
	"vigilant",	"member of a vigilance committee",
	"vigorous",	"strong, energetic",
	"vilify",	"slander, say evil things",
	"vindictive",	"having a desire to revenge",
	"virago",	"a loud, domineering woman; a scold or nag",
	"visceral",	"of the internal organs of the body",
	"vitiate",	"lower the quality; weaken the strength",
	"vituperate",	"curse, abuse in words",
	"vivacious",	"lively, high-spirited",
	"volatile",	"changeable, inconstant, fickle, unstable, explosive",
	"volubility",	"fluency, verbosity, easy use of spoken language",
	"voluble",	"fluent",
	"voluminous",	"occupying much space",
	"waft",	"scent, waving movement; carry lightly through",
	"wag",	"merry person",
	"wage",	"payment, carry on, engage in (war)",
	"warmonger",	"person who stirs up war",
	"warp",	"become bent",
	"warrant",	"authority, written order, guarantee",
	"wary",	"cautious",
	"weave",	"make (threads) into cloth",
	"weigh",	"measure hoe heavy smth is",
	"welter",	"turmoil; a bewildering jumble",
	"wend",	"to go, proceed",
	"whimsical",	"full of odd and fanciful ideas",
	"wince",	"show bodily or mental pain",
	"woo",	"try to win",
	"yarn",	"tale, story; fibers for knitting"
)

function DisplayWord()
{
	if( (index % 2) == 1)
	{
		index = index - 1
	}
	
	document.forms[0].display.value = dictionary[ index ]
}

function DisplayDefinition()
{
	if( (index % 2) == 0)
	{
		index = index + 1
	}
	
	document.forms[0].display.value = dictionary[ index ]
}

function NewWord()
{
	var oldIndex = index
	
	while( oldIndex == index )
	{
		index = Math.floor(Math.random() * (dictionary.length/2))
		index *= 2
		DisplayWord()
	}
}

function Flip()
{
	if( (index%2) == 0 )
		DisplayDefinition()
	else
		DisplayWord()
}
